"""add matched_skills, experience_match, keyword_match to analyses

Revision ID: 386b4fad9982
Revises: b1a9606c05b1
Create Date: 2026-08-30 11:52:50.915925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386b4fad9982'
down_revision: Union[str, Sequence[str], None] = 'b1a9606c05b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('matched_skills', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('experience_match', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('keyword_match', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'keyword_match')
    op.drop_column('analyses', 'experience_match')
    op.drop_column('analyses', 'matched_skills')
    # ### end Alembic commands ###
